language: python
services:
  - memcached
  - redis-server
# Use Travis' build matrix and exclude functions rather than running tox
# directly so that we can run the builds in parallel and get coverage reports
# for each Python/Django version combo
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create database travis_ci_test2;' -U postgres
install:
  - pip install -U pip  # make sure we have the latest version
  - pip install -e .
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
  - flake8
after_success:
  - coveralls
env:
  - TOX_ENV="dj14-py26"
  - TOX_ENV="dj14-py27"
  - TOX_ENV="dj15-py26"
  - TOX_ENV="dj15-py27"
  - TOX_ENV="dj15-py33"
  - TOX_ENV="dj15-py34"
  - TOX_ENV="dj16-py26"
  - TOX_ENV="dj16-py27"
  - TOX_ENV="dj16-py33"
  - TOX_ENV="dj16-py34"
  - TOX_ENV="dj17-py27"
  - TOX_ENV="dj17-py33"
  - TOX_ENV="dj17-py34"
  - TOX_ENV="dj18-py27"
  - TOX_ENV="dj18-py33"
  - TOX_ENV="dj18-py34"
  - TOX_ENV="dj19-py27"
  - TOX_ENV="dj19-py34"
  - TOX_ENV="dj19-py35"
  - TOX_ENV="dj110-py27"
  - TOX_ENV="dj110-py34"
  - TOX_ENV="dj110-py35"
  - TOX_ENV="py27-flake8"
  - TOX_ENV="py35-flake8"
  - TOX_ENV="docs"
# Adding sudo: False tells Travis to use their container-based infrastructure, which is somewhat faster.
sudo: False
